name: camunda-bpm
home: https://github.com/hmcts/camunda-bpm
version: 0.0.47
description: Camunda bpm
maintainers:
  - name: HMCTS Platform Operations team
apiVersion: v2
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/' 
