name: camunda-bpm
home: https://github.com/hmcts/camunda-bpm
version: 0.0.23
description: Camunda bpm
maintainers:
  - name: HMCTS Platform engineering team
apiVersion: v2
dependencies:
  - name: java
    version: 3.7.6
    repository: '@hmctspublic' 
