java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  disableKeyVaults: true
  environment:
    CAMUNDA_DB_HOST: "{{ .Release.Name }}-postgresql"
    CAMUNDA_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    CAMUNDA_DB_USER_NAME: "{{ .Values.postgresql.postgresqlUsername}}"
    CAMUNDA_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
    SPRING_PROFILES_ACTIVE: default
    SPRING_FLYWAY_ENABLED: false
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
  postgresql:
    enabled: true
